// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/presentation/bloc/movies/watchlist_movie_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i10;
import 'package:dartz/dartz.dart' as _i8;
import 'package:ditonton/common/failure.dart' as _i11;
import 'package:ditonton/domain/entities/movie_entities/movie.dart' as _i12;
import 'package:ditonton/domain/entities/movie_entities/movie_detail.dart'
    as _i13;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i9;
import 'package:ditonton/domain/usecases/movie_usecases/get_watchlist_movies.dart'
    as _i2;
import 'package:ditonton/domain/usecases/movie_usecases/get_watchlist_status.dart'
    as _i3;
import 'package:ditonton/domain/usecases/movie_usecases/remove_watchlist.dart'
    as _i5;
import 'package:ditonton/domain/usecases/movie_usecases/save_watchlist.dart'
    as _i4;
import 'package:ditonton/presentation/bloc_provider/movie_provider/watchlist_movies/watchlist_movies_bloc.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetWatchlistMovies_0 extends _i1.Fake
    implements _i2.GetWatchlistMovies {}

class _FakeGetWatchListStatus_1 extends _i1.Fake
    implements _i3.GetWatchListStatus {}

class _FakeSaveWatchlist_2 extends _i1.Fake implements _i4.SaveWatchlist {}

class _FakeRemoveWatchlist_3 extends _i1.Fake implements _i5.RemoveWatchlist {}

class _FakeWatchlistMoviesState_4 extends _i1.Fake
    implements _i6.WatchlistMoviesState {}

class _FakeStreamSubscription_5<T> extends _i1.Fake
    implements _i7.StreamSubscription<T> {}

class _FakeEither_6<L, R> extends _i1.Fake implements _i8.Either<L, R> {}

class _FakeMovieRepository_7 extends _i1.Fake implements _i9.MovieRepository {}

/// A class which mocks [WatchlistMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMoviesBloc extends _i1.Mock
    implements _i6.WatchlistMoviesBloc {
  MockWatchlistMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistMovies),
          returnValue: _FakeGetWatchlistMovies_0()) as _i2.GetWatchlistMovies);
  @override
  _i3.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
          returnValue: _FakeGetWatchListStatus_1()) as _i3.GetWatchListStatus);
  @override
  _i4.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlist_2()) as _i4.SaveWatchlist);
  @override
  _i5.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
          returnValue: _FakeRemoveWatchlist_3()) as _i5.RemoveWatchlist);
  @override
  _i6.WatchlistMoviesState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeWatchlistMoviesState_4()) as _i6.WatchlistMoviesState);
  @override
  _i7.Stream<_i6.WatchlistMoviesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.WatchlistMoviesState>.empty())
          as _i7.Stream<_i6.WatchlistMoviesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.WatchlistMoviesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.WatchlistMoviesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i7.Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>
      transformEvents(
              _i7.Stream<_i6.WatchlistMoviesEvent>? events,
              _i10.TransitionFunction<_i6.WatchlistMoviesEvent,
                      _i6.WatchlistMoviesState>?
                  transitionFn) =>
          (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>.empty()) as _i7
              .Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>);
  @override
  void emit(_i6.WatchlistMoviesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.WatchlistMoviesEvent>(
          _i10.EventHandler<E, _i6.WatchlistMoviesState>? handler,
          {_i10.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i7.Stream<_i6.WatchlistMoviesState> mapEventToState(
          _i6.WatchlistMoviesEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i6.WatchlistMoviesState>.empty())
          as _i7.Stream<_i6.WatchlistMoviesState>);
  @override
  void onTransition(
          _i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>
      transformTransitions(
              _i7.Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>.empty())
              as _i7.Stream<
                  _i10.Transition<_i6.WatchlistMoviesEvent, _i6.WatchlistMoviesState>>);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.StreamSubscription<_i6.WatchlistMoviesState> listen(
          void Function(_i6.WatchlistMoviesState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue:
                  _FakeStreamSubscription_5<_i6.WatchlistMoviesState>())
          as _i7.StreamSubscription<_i6.WatchlistMoviesState>);
  @override
  void onChange(_i10.Change<_i6.WatchlistMoviesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i2.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Either<_i11.Failure, List<_i12.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i8.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_6<_i11.Failure, List<_i12.Movie>>())) as _i7
          .Future<_i8.Either<_i11.Failure, List<_i12.Movie>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i3.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_7()) as _i9.MovieRepository);
  @override
  _i7.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i4.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_7()) as _i9.MovieRepository);
  @override
  _i7.Future<_i8.Either<_i11.Failure, String>> execute(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i8.Either<_i11.Failure, String>>.value(
                  _FakeEither_6<_i11.Failure, String>()))
          as _i7.Future<_i8.Either<_i11.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i5.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_7()) as _i9.MovieRepository);
  @override
  _i7.Future<_i8.Either<_i11.Failure, String>> execute(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i8.Either<_i11.Failure, String>>.value(
                  _FakeEither_6<_i11.Failure, String>()))
          as _i7.Future<_i8.Either<_i11.Failure, String>>);
}
